"""empty message

Revision ID: 67d0e4ddb51a
Revises: e4a77cd4fb94
Create Date: 2019-09-17 18:03:16.710639

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '67d0e4ddb51a'
down_revision = 'e4a77cd4fb94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('banner', 'name')
    op.drop_column('banner', 'img_url')
    op.drop_column('banner', 'link_to')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banner', sa.Column('link_to', mysql.VARCHAR(length=200), nullable=False))
    op.add_column('banner', sa.Column('img_url', mysql.VARCHAR(length=200), nullable=False))
    op.add_column('banner', sa.Column('name', mysql.VARCHAR(length=200), nullable=False))
    # ### end Alembic commands ###
