"""empty message

Revision ID: d23b52c199b0
Revises: 67d0e4ddb51a
Create Date: 2019-09-17 18:03:33.726177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd23b52c199b0'
down_revision = '67d0e4ddb51a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banner', sa.Column('img_url', sa.String(length=255), nullable=False))
    op.add_column('banner', sa.Column('link_to', sa.String(length=255), nullable=False))
    op.add_column('banner', sa.Column('name', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('banner', 'name')
    op.drop_column('banner', 'link_to')
    op.drop_column('banner', 'img_url')
    # ### end Alembic commands ###
